#!/bin/sh

abs_path=$(cd `dirname $0`; pwd)
root_path=$(cd "$abs_path/../../"; pwd) #gm_service目录

#切换到web目录作为根目录
cd $root_path/mysite

who_id=$(id -u)
who_name=$(id -u -n)

export PYTHONPATH=$root_path:$PYTHONPATH

# if [[ $who_id -eq 0 ]]; then
# 	exec /usr/bin/setuidgid superman $abs_path/real_run
# elif [[ $who_name -eq superman ]];then
	exec $abs_path/real_run
# else
# 	echo "current user can't run."
# fi
